/**:
  ros__parameters:
    back_pole:
      frame_id: world
      orientation_rpy: [0.0, 0.0, 0.0]
      position: [2.0, 0.2, 0.9]
      size: [1.8, 0.05, 0.0]
      type: cylinder
    bottom_wall:
      frame_id: world
      orientation_rpy: [0.0, 0.0, 0.0]
      position: [2.0, 0.0, 0.25]
      size: [0.1, 2.0, 0.5]
      type: box
    d_safe: 0.05
    left_pillar:
      frame_id: world
      orientation_rpy: [0.0, 0.0, 0.0]
      position: [2.0, 0.7, 1.15]
      size: [0.1, 0.6, 0.9]
      type: box
    obstacles: [bottom_wall, top_wall, left_pillar, right_pillar, back_pole]
    right_pillar:
      frame_id: world
      orientation_rpy: [0.0, 0.0, 0.0]
      position: [2.0, -0.7, 1.15]
      size: [0.1, 0.6, 0.9]
      type: box
    target_structure:
      frame_id: world
      local_normal: [-1.0, 0.0, 0.0]
      mesh_file: package://irb2600_coating_cell/meshes/curved_panel.stl
      orientation_rpy: [0.0, 0.0, 0.0]
      position: [0.7, -1.2, 1.5]
      size: [0.05, 5.0, 2.0]
    top_wall:
      frame_id: world
      orientation_rpy: [0.0, 0.0, 0.0]
      position: [2.0, 0.0, 1.9]
      size: [0.1, 2.0, 0.8]
      type: box
    workspace_clear_margin: 0.15
